title: "Han Kee Lian"
logo: /assets/profile.png   # optional - place your profile photo in /assets/
description: "Machine Learning Engineer | AI Systems Developer | Data Scientist"
url: "https://hkl19.github.io"
github_username: hkl19

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Layout settings
show_downloads: false
minimal_mistakes_skin: "air"  # try 'dark', 'dirt', 'mint', etc.

# Navigation bar
header_pages:
  - index.md
  - projects.md
  - contact.md

# Social links
author:
  name: "Han Kee Lian"
  email: "han.lian19@alumni.imperial.ac.uk"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hkl19"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/hankee-lian"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:han.lian19@alumni.imperial.ac.uk"
